tls:
  certificates:
    - certFile: /etc/certs/servercert.pem
      keyFile: /etc/certs/serverkey.pem
      stores:
        - default
    - certFile: /etc/certs/cacert.pem
      keyFile: /etc/certs/cakey.pem
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/servercert.pem
        keyFile: /etc/certs/serverkey.pem
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384